//
//  Constants.swift
//  PGH Bus Tracker
//
//  Created by Eric Fang on 4/19/17.
//  Copyright © 2017 Eric Fang. All rights reserved.
//

import Foundation

struct Constants {
    static let buses = ["1":"Freeport Road",
                 "2":"Mount Royal",
                 "4":"Troy Hill",
                 "6":"Spring Hill",
                 "7":"Spring Garden",
                 "8":"Perrysville",
                 "11":"Fineview",
                 "12":"McKnight",
                 "13":"Bellevue",
                 "14":"Ohio Valley",
                 "15":"Charles",
                 "16":"Brighton",
                 "17":"Shadeland",
                 "18":"Manchester",
                 "19L": "Emsworth Limited",
                 "20":"Kennedy",
                 "21":"Coraopolis",
                 "22":"McCoy",
                 "24":"West Park",
                 "26":"Chartiers",
                 "27":"Fairywood",
                 "28X": "Airport Flyer",
                 "29":"Robinson",
                 "31":"Bridgeville",
                 "36":"Banksville",
                 "38":"Green Tree",
                 "39":"Brookline",
                 "40":"Mount Washington",
                 "41":"Bower Hill",
                 "43":"Bailey",
                 "44":"Knoxville",
                 "48":"Arlington",
                 "51":"Carrick",
                 "51L": "Carrick Limited",
                 "52L": "Homeville Limited",
                 "53":"Homestead Park",
                 "53L": "Homestead Park Limited",
                 "54":"North Side-Oakland-South Side",
                 "55":"Glassport",
                 "56":"Lincoln Place",
                 "57":"Hazelwood",
                 "58":"Greenfield",
                 "59":"Mon Valley",
                 "60":"Walnut-Crawford Village",
                 "61A": "North Braddock",
                 "61B": "Braddock-Swissvale",
                 "61C": "McKeesport-Homestead",
                 "61D": "Murray",
                 "64":"Lawrenceville-Waterfront",
                 "65":"Squirrel Hill",
                 "67":"Monroeville",
                 "68":"Braddock Hills",
                 "69":"Trafford",
                 "71":"Edgewood Town Center",
                 "71A": "Negley",
                 "71B": "Highland Park",
                 "71C": "Point Breeze",
                 "71D": "Hamilton",
                 "74":"Homewood-Squirrel Hill",
                 "75":"Ellsworth",
                 "77":"Penn Hills",
                 "78":"Oakmont",
                 "79":"East Hills",
                 "81":"Oak Hill",
                 "82":"Lincoln",
                 "83":"Bedford Hill",
                 "86":"Liberty",
                 "87":"Friendship",
                 "88":"Penn",
                 "89":"Garfield Commons",
                 "91":"Butler Street",
                 "93":"Lawrenceville-Hazelwood",
                 "BLLB": "Library via Overbrook",
                 "BLSV": "South Hills Village via Overbrook",
                 "G2":"West Busway",
                 "G3":"Moon Flyer",
                 "G31": "Bridgeville Flyer",
                 "O1":"Ross Flyer",
                 "O12": "McKnight Flyer",
                 "O5":"Thompson Run Flyer",
                 "P1":"East BuswayAll Stops",
                 "P10": "Allegheny Valley Flyer",
                 "P12": "Holiday Park Flyer",
                 "P13": "Mount Royal Flyer",
                 "P16": "Penn Hills Flyer",
                 "P17": "Lincoln Park Flyer",
                 "P2":"East Busway Short",
                 "P3":"East BuswayOakland",
                 "P67": "Monroeville Flyer",
                 "P68": "Braddock Hills Flyer",
                 "P69": "Trafford Flyer",
                 "P7":"McKeesport Flyer",
                 "P71": "Swissvale Flyer",
                 "P76": "Lincoln Highway Flyer",
                 "P78": "Oakmont Flyer",
                 "RED": "Castle Shannon via Beechview",
                 "Y1":"Large Flyer",
                 "Y45": "Baldwin Manor Flyer",
                 "Y46": "Elizabeth Flyer",
                 "Y47": "Curry Flyer",
                 "Y49": "Prospect Flyer"]
    static let key = // your own API key
}
